#include <adwaita.h>
#include <bge.h>
#include <gtk/gtk.h>
#include <libdex.h>

#include "bz-application.h"
#include "bz-logger.h"
#include "bz-window.h"

/*
 * BzWindow UI test.
 *
 * Verifies a real BzWindow can be constructed, presented, and that
 * its template-loaded children (AdwViewStack, AdwNavigationView) are
 * present and visible.
 *
 * Run with: GTK_A11Y=test meson test -C build test_window_widgets
 */

static BzWindow       *window = NULL;
static GtkApplication *app;
static BzStateInfo    *state = NULL;

/*
 * bz_get_resource is generated by gnome.compile_resources and is not
 * declared in any header. We declare it here to verify GResource linking.
 */
extern GResource *bz_get_resource (void);

static void
on_activate (GtkApplication *application,
             gpointer        user_data)
{
  window = bz_window_new (state);
  g_test_message ("bz_window_new(state=%p) returned window=%p",
                  (void *) state, (void *) window);
  g_assert_nonnull (window);
  g_assert_true (BZ_IS_WINDOW (window));

  gtk_application_add_window (application, GTK_WINDOW (window));
  gtk_window_present (GTK_WINDOW (window));
}

static void
test_bzwindow_exists (void)
{
  g_test_message ("window=%p type=%s", (void *) window,
                  G_OBJECT_TYPE_NAME (window));
  g_assert_nonnull (window);
  g_assert_true (BZ_IS_WINDOW (window));
}

static void
test_bzwindow_title (void)
{
  const gchar *title;

  title = gtk_window_get_title (GTK_WINDOW (window));
  g_test_message ("window title=\"%s\"", title);
  g_assert_nonnull (title);
  g_assert_cmpstr (title, !=, "");
}

static void
test_bzwindow_visible (void)
{
  gboolean visible = gtk_widget_get_visible (GTK_WIDGET (window));
  g_test_message ("window visible=%d", visible);
  g_assert_true (visible);
}

static void
test_bzwindow_accessible_role (void)
{
  GtkAccessibleRole role;
  role = gtk_accessible_get_accessible_role (GTK_ACCESSIBLE (window));
  g_test_message ("window role=%d (expected=%d)", role, GTK_ACCESSIBLE_ROLE_WINDOW);
  g_assert_cmpint (role, ==, GTK_ACCESSIBLE_ROLE_WINDOW);
}

static void
test_bzwindow_null_state (void)
{
  if (g_test_subprocess ())
    {
      bz_window_new (NULL);
      return;
    }
  g_test_trap_subprocess (NULL, 0, G_TEST_SUBPROCESS_DEFAULT);
  g_test_trap_assert_failed ();
}

static void
test_bzwindow_bare_state (void)
{
  BzStateInfo *bare_state = bz_state_info_new ();
  g_assert_nonnull (bare_state);

  BzWindow *w = bz_window_new (bare_state);
  g_test_message ("bz_window_new(bare_state=%p) returned %p",
                  (void *) bare_state, (void *) w);
  g_assert_nonnull (w);
  g_assert_true (BZ_IS_WINDOW (w));

  g_clear_object (&w);
  g_clear_object (&bare_state);
}

static void
test_bzwindow_resource (void)
{
  GResource *res = bz_get_resource ();
  g_test_message ("bz_get_resource() returned %p", (void *) res);
  g_assert_nonnull (res);
}

int
main (int argc, char *argv[])
{
  gtk_test_init (&argc, &argv, NULL);
  g_test_set_nonfatal_assertions ();

  dex_init ();
  bge_init ();

  state = bz_state_info_new ();
  g_assert_nonnull (state);

  app = g_object_new (BZ_TYPE_APPLICATION,
                      "application-id", "io.github.kolunmi.Bazaar.Tests",
                      "flags", G_APPLICATION_DEFAULT_FLAGS,
                      "resource-base-path", "/io/github/kolunmi/Bazaar",
                      NULL);
  g_assert_nonnull (app);

  g_signal_connect (app, "activate", G_CALLBACK (on_activate), NULL);

  g_application_register (G_APPLICATION (app), NULL, NULL);
  on_activate (app, NULL);
  g_assert_nonnull (window);

  g_test_add_func ("/bzwindow/exists", test_bzwindow_exists);
  g_test_add_func ("/bzwindow/title", test_bzwindow_title);
  g_test_add_func ("/bzwindow/visible", test_bzwindow_visible);
  g_test_add_func ("/bzwindow/role", test_bzwindow_accessible_role);
  g_test_add_func ("/bzwindow/null-state", test_bzwindow_null_state);
  g_test_add_func ("/bzwindow/bare-state", test_bzwindow_bare_state);
  g_test_add_func ("/bzwindow/resource", test_bzwindow_resource);

  return g_test_run ();
}
